@startuml

participant "Client" as B
participant "Server" as P

activate P
B -> P: ClientHello
activate B
P -> B: ServerHello

P -> B: Certificat
P -> B: Échange de clés serveur (si nécessaire)
P -> B: ServerHelloDone

B -> P: Échange de clés client
B -> P: ChangeCipherSpec
B -> P: Finished

P -> B: ChangeCipherSpec
P -> B: Finished

@enduml