@startuml
left to right direction

actor "Testeur" as tester

rectangle "Burpsuite Tek-Up Edition" as rec {

    usecase "Intercepter le trafic HTTP/S" as intercept
    usecase "Modifier des requêtes/réponses" as modify
    usecase "Envoyer des requêtes/réponses" as send 
    usecase "Supprimer des requêtes/réponses" as drop 
    usecase "Marquer des requêtes/réponses" as bookmark 
    usecase "Exécuter des listes de payloads" as intruder 
    usecase "Afficher l'historique des requêtes/réponses" as log 
    usecase "Afficher les requêtes/réponses" as showReq
    usecase "Afficher l'en-tête des requêtes/réponses" as showHeader
    usecase "Afficher le corps des requêtes/réponses" as showBody
    usecase "Ajouter une liste de payloads" as addPayloadList 

    usecase "Gérer les listes de domaines/urlPatterns/wordlists prohibées" as domainBlock 
    usecase "Ajouter une liste" as addList
    usecase "Modifier une liste" as modList
    usecase "Supprimer une liste" as delList
}

domainBlock <|--- addList 
domainBlock <|--- modList 
domainBlock <|--- delList 

showReq <|--- showHeader
showReq <|--- showBody 

tester -- modify
tester -- addPayloadList 
modify .right. addPayloadList
tester -- send 
tester -- drop
tester -- bookmark 
tester -- log 
tester -- showReq 
tester -- domainBlock 
modify ...> intercept : <<include>>
send <.... intruder : <<extends>>

@enduml
